import { makeStyles } from '@material-ui/core';
import { MEMORY } from '../../constants';
// import { red200 } from 'material-ui/styles/colors';

const useStyles = makeStyles(() => ({
  imageWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  switcherWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  switcher: {
    zIndex: 1000,
  },
  button: {
    height: '38px',
    marginLeft: 'auto',
    marginRight: '1vw',
  },
  sheet4: {
    background: `url(${MEMORY.sheet})`,
    backgroundSize: 'cover',
    width: '22%',
    height: '28%',
  },
  sheet8: {
    background: `url(${MEMORY.sheet})`,
    backgroundSize: 'cover',
    width: '22%',
    height: '22%',
    margin: '1vh 1vw',
  },
  sheet10: {
    background: `url(${MEMORY.sheet})`,
    backgroundSize: 'cover',
    width: '17%',
    height: '20%',
    margin: '0.75vh 0.75vw',
  },
  imageNone: {
    opacity: '0',
  },
  image: {
    width: '100%',
    height: 'calc(width * 0.6666)',
    transform: 'rotateY(180deg)',
  },
  gameWrapper: {
    display: 'flex',
    //flexWrap: 'wrap',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100vw',
    minWidth: '500px',
    padding: '2%',
    height: 'calc(100vh - 80px)',
    background: `url(${MEMORY.background})`,
    backgroundSize: 'cover',
    color: 'white',
    '&:before': {
      content: '""',
      position: 'absolute',
      top: 80,
      left: 0,
      width: '100%',
      height: 'calc(100vh - 80px)',
      background: 'rgba(0, 0, 0, 0.05)',
    },
  },
  cardsWrapper: {
    zIndex: 1000,
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '90vw',
    height: '75vh',
    flexWrap: 'wrap',
    marginBottom: '3vh',
    paddingTop: '3vh',
  },
  card4: {
    width: '22%',
    height: '28%',
    transition: '0.6s',
    transformStyle: 'preserve-3d',
    transform: 'rotateY(180deg)',
  },
  card8: {
    width: '22%',
    height: '22%',
    margin: '1vh 1vw',
    transition: '0.6s',
    transformStyle: 'preserve-3d',
    transform: 'rotateY(180deg)',
  },
  card10: {
    width: '17%',
    height: '20%',
    margin: '0.75vh 0.75vw',
    transition: '0.6s',
    transformStyle: 'preserve-3d',
    transform: 'rotateY(180deg)',
  },
  content: {
    marginTop: 'auto',
  },
  cardWithText4: {
    width: '22%',
    height: '28%',
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    transition: '0.6s',
    transformStyle: 'preserve-3d',
    transform: 'rotateY(180deg)',
  },
  cardWithText8: {
    width: '22%',
    height: '22%',
    margin: '1vh 1vw',
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    transition: '0.6s',
    transformStyle: 'preserve-3d',
    transform: 'rotateY(180deg)',
  },
  cardWithText10: {
    width: '17%',
    height: '20%',
    margin: '0.75vh 0.75vw',
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    transition: '0.6s',
    transformStyle: 'preserve-3d',
    transform: 'rotateY(180deg)',
  },
  text: {
    maxWidth: '100%',
    fontSize: '2vw',
    margin: '0 1%',
    transform: 'rotateY(180deg)',
    userSelect: 'none',
  },
  textNone: {
    fontSize: '0',
  },
  controlsWrapper: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 1000,
    '&:after': {
      content: '""',
      zIndex: 1000,
    },
  },
  selectorsWrapper: {
    display: 'flex',
    flexDirection: 'column',
  },
  leftWrapper: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  canselBtnWrapper: {
    marginLeft: 'auto',
  },
}));

export default useStyles;
