export const SET_IS_LOADING = 'APP/SET_IS_LOADING';

export const SET_USER_DATA = 'USER/SET_USER_DATA';
export const SET_FAILED_ATTEMPT = 'USER/SET_FAILED_ATTEMPT';
export const SET_IS_LOGGED_IN = 'USER/SET_IS_LOGGED_IN';
export const SET_IS_REGISTRED = 'USER/SET_IS_REGISTRED';
